### ISSUE TITLE
Error: Launching server using command `${workspaceFolder}/.vscode/.dotnet/dotnet` failed.

### ISSUE THREAD

**Issue by valord577** [josetr/cmake-language-support#11]
Due to network reasons, the automatic download of dotnet-runtime always fails, I use a custom environment:

```
// .vscode/settings.json
{
    "dotnetAcquisitionExtension.existingDotnetPath": [
        {
            "extensionId": "josetr.cmake-language-support-vscode",
            "path": "${workspaceFolder}/.vscode/.dotnet/dotnet"
        }
    ]
}
```

But I get error:

```
[Error - 7:13:54 AM] Starting client failed
Error: Launching server using command ${workspaceFolder}/.vscode/.dotnet/dotnet failed.
	at /home/deker/.vscode-server/extensions/josetr.cmake-language-support-vscode-0.0.4/dist/extension.js:1:225401
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by markgomez** [comment]
> Error: Launching server using command ${workspaceFolder}/.vscode/.dotnet/dotnet failed.
> 	at /home/deker/.vscode-server/extensions/josetr.cmake-language-support-vscode-0.0.4/dist/extension.js:1:225401

It looks like variable substitution isn't working for the `${workspaceFolder}` [predefined variable](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables). I think you'll have to hardcode the literal absolute path.

**Comment by valord577** [comment]
> Is `${workspaceFolder}/.vscode/.dotnet/dotnet` really a valid dotnet path? If so, which .NET Runtime version is it?

`${workspaceFolder}` - [VSCode Predefined variables](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables)

**Comment by josetr** [comment]
I've added a new `cmake.languageSupport.dotnetPath` option which should solve your problem. See README for more info.
