### ISSUE TITLE
VSCode can't activate extension because it depends on unknown extension ms-dotnettools.vscode-dotnet-runtime 

### ISSUE THREAD

**Issue by a5066987** [josetr/cmake-language-support#13]
I'm trying to install your extension through vsix, but the machine I use doesn't have Internet access.

Anyway to install your extension offline?

**Comment by jsrdzhk** [comment]
I have installed .net sdk and runtime manually and set dotnet path on settings as below:
```json
"dotnetAcquisitionExtension.existingDotnetPath": [
        {
            "extensionId": "josetr.cmake-language-support-vscode",
            "path": "/usr/bin/dotnet"
        },
        {
            "extensionId": "msazurermtools.azurerm-vscode-tools",
            "path": "/usr/bin/dotnet"
        }
    ],
```
However,I still get error message from vscode each time I open the cmake project on vscode:
```
Failed to run .NET runtime. You may be missing key Linux libraries. Install them now?
```
I use vscode remote develop.The host machine is macintosh and the remote machine is cent os 7.
dotnet runtime installed on remote machine is:
```
➜  server git:(multi_cpp_md) dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by josetr** [comment]
I've decided to keep the automatic .NET Runtime installer. It works for most people. I hope Microsoft eventually will properly make it work for all the missing scenarios.

For the rest, I've updated the documentation explaining how to manually install the .NET runtime and point to it using the newly added `cmake.languageSupport.dotnetPath` vscode option.
