### ISSUE TITLE
[suggest] Change the LOGO of this extension?

### ISSUE THREAD

**Issue by hwhsu1231** [josetr/cmake-language-support#14]
Compared to other CMake-related extensions, the CMake icon which it is using is kind of......**weird**. (The green part of it is too big).

Because this extension is used to replace [vs.language.cmake](https://github.com/twxs/vs.language.cmake), which is the original dependency of [vscode-cmake-tools](https://github.com/microsoft/vscode-cmake-tools), since the version 1.11 of CMake-Tools (https://github.com/microsoft/vscode-cmake-tools/pull/2267), I recommend that it use a better CMake icon. 

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/173498849-8212ce93-0175-4d37-8b85-47ffc3703c2b.png)

**Comment by josetr** [comment]
I'm happy to change it if someone has a better alternative with a friendly license.

**Comment by hwhsu1231** [comment]
How about this one?

https://commons.wikimedia.org/wiki/File:Cmake.svg

**Comment by josetr** [comment]
Done.
