### ISSUE TITLE
[bug] The color goes wrong when using `\(` and `\)` in `$ENV{}`.

### ISSUE THREAD

**Issue by hwhsu1231** [josetr/cmake-language-support#19]
### Version

- CMake Language Support: **v0.0.4**

### Examples

```cmake
find_program(DOXYGEN_EXECUTABLE
  NAMES doxygen
  PATHS "$ENV{ProgramFiles}/doxygen/bin"
        "$ENV{ProgramFiles\(x86\)}/doxygen/bin"
  # REQUIRED
)
```

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/179516814-714aae35-a707-42be-9ac7-9ea873a31f2b.png)

**Comment by josetr** [comment]
Fixed.
