### ISSUE TITLE
[bug] intelliSense about `break()` command in `foreach()` goes wrong.

### ISSUE THREAD

**Issue by hwhsu1231** [josetr/cmake-language-support#23]
### Problem Descriptions

Theoratically, the following code should be fine. It is because `break()` command is actually inside the `foreach()` although there is a `if()/else()/endif()` command between them.

```cmake
foreach(ARG ${ARGUMENTS_BUILD})
    if(${ARG} STREQUAL "all")
        set(CONAN_BUILD_POLICY ${CONAN_BUILD_POLICY} --build)
        break()
    else()
        set(CONAN_BUILD_POLICY ${CONAN_BUILD_POLICY} --build=${ARG})
    endif()
endforeach()
```

However, the intelliSense showed that:

```
'break' can only appear inside a 'foreach' or 'while' statement.
```

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/193438826-45653495-0b91-47f1-b87e-c2dca683bb00.png)
![image](https://user-images.githubusercontent.com/71438617/193438857-9af479ea-73b1-4755-9a00-fc3e14d70e7c.png)

### Environments and Versions

- CMake Language Support: **v0.0.4**

**Comment by tqfx** [comment]
`continue()` as well

 **Screenshots**

![image](https://user-images.githubusercontent.com/59302530/195083677-e035cfe6-1886-4b0f-be85-3960b3df15be.png)

**Comment by josetr** [comment]
Fixed
