### ISSUE TITLE
using together with `Vim` extension, the extension parses wrong files since today's update

### ISSUE THREAD

**Issue by FeignClaims** [josetr/cmake-language-support#25]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/62583114/195971676-f527423a-5560-47da-84b9-ca73ea11bf73.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/62583114/195971650-01dfc4b9-f186-4a6d-a3fa-2655db79d273.png">

**Comment by josetr** [comment]
* Which extension are you using? 
* Does it happen as well in other file types?
* What errors are you getting? (I cant see them)

**Comment by FeignClaims** [comment]
- I've tried to disable all my rust extensions, but it still gets wrong.
- `*.json`, `.clang-format`, `clangd`, `*.py`, `.gitignore`, `*.md`..., maybe all file types, get wrong **after being edited**.
- Some errors is showed down here.
<img width="875" alt="image" src="https://user-images.githubusercontent.com/62583114/195971899-82e61a61-96c3-4777-a1de-5f324d9600ec.png">
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/62583114/195972013-5c5be297-a799-4242-a83a-94400c1b80f7.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/62583114/195972049-454ef914-a7eb-4003-90dd-e979d11b33b1.png">

**Comment by FeignClaims** [comment]
I've found the problem. After the update, The ``CMake Language Support`` extension conflicts with the ``Vim`` extension. Is there a possible way to fix this? Or should I issue this to the ``Vim`` extension repository?
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/62583114/195972841-cca2811f-6264-4d43-b2c7-5988eea5c941.png">

**Comment by josetr** [comment]
I've published a new version 0.0.6, please let me know if the issue has been fixed now.

**Comment by FeignClaims** [comment]
It was fixed! Thanks.
