### ISSUE TITLE
Missing some commands/variables/parameters

### ISSUE THREAD

**Issue by Leopard20** [josetr/cmake-language-support#3]
Some commands/variables/parameters from the latest versions of CMake seem to be missing.

I'll try to update this list as I come across them:
* `NO_CACHE` in `find_library`: https://cmake.org/cmake/help/latest/command/find_library.html
* Several generator expressions, such as `TARGET_FILE_DIR`: https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html
* `CMAKE_CXX_COMPILER_ID`, `CMAKE_CXX_FLAGS`, etc.

**Comment by josetr** [comment]
Fixed but feel free to open it again if it becomes too outdated again since the database is still generated at build time.
