### ISSUE TITLE
only half of syntax highlight

### ISSUE THREAD

**Issue by atsju** [josetr/cmake-language-support#30]
The syntax highlight is absolutely not like in your preview. 
See an example of my files: 
![image](https://user-images.githubusercontent.com/4628382/210365100-566419bd-779d-4ff1-ab38-6434f5f1a5aa.png)
Can you help fix that ?

I note 15 uncaught errors under runtime status if it can help : `Cannot read properties of undefined (reading 'document')`

Please come back to me if you need more information.

**Comment by josetr** [comment]
Is it happening in all files or only in this one?

Ideally, I would need the source code that reproduces the issue.

**Comment by atsju** [comment]
All files.
I can not provide the source code of professional code. You can understand that as your sources are closed.
Anyway, same is reproduced with any code, as for example with folder https://github.com/ObKo/stm32-cmake/tree/master/examples/blinky
Is there debug information I can share ?

**Comment by josetr** [comment]
I completely understand, that's why I was only talking about the necessary source code that reproduces the issue (which is usually a few lines long and can be filled with random data)

Can you try disabling all the vscode plugins that you have to make sure one of them is not conflicting with this one?

Mind sharing your operating system?

I've cloned the repo that you have provided and it works perfectly well for me: 

![image](https://user-images.githubusercontent.com/37419832/210374000-624b542f-6b75-43ce-9845-96b70bd01f5c.png)

**Comment by atsju** [comment]
I run windows 10
I disabled absolutely ALL extensions except yours:
![image](https://user-images.githubusercontent.com/4628382/210376174-0b010575-ed17-45b0-afbb-b996cc8a53d9.png)

**Comment by josetr** [comment]
I just noticed that I'm seeing the same error as you, but in my case, the extension still continues to work.


Do you see any errors here:

![image](https://user-images.githubusercontent.com/37419832/210376846-7330783a-2370-4362-9402-242e7692dd14.png)

**Comment by atsju** [comment]
everything fine here
![image](https://user-images.githubusercontent.com/4628382/210377425-18428e5a-2b05-46f7-9d45-277e4d49a798.png)
![image](https://user-images.githubusercontent.com/4628382/210377534-9c3f9b62-b9c4-4f70-8c39-3ec842226866.png)

**Comment by josetr** [comment]
I've released a new version 0.0.8 which should fix the issue that you've mentioned. Please let me know if that is enough to get the whole extension to start working.

**Comment by atsju** [comment]
No better in 0.8.0. No color, still runtime status errors, no error in console.
![image](https://user-images.githubusercontent.com/4628382/210503097-9d7540ec-8534-4bdc-a56a-7f138941dea2.png)

**Comment by josetr** [comment]
0.0.9 available now, please try it out 👍

**Comment by atsju** [comment]
not OK (but no more uncaught error ?)
![image](https://user-images.githubusercontent.com/4628382/210528963-b9b9dfb9-bcf9-43b2-b238-781855e16e44.png)

Also let me remind you of this issue: https://github.com/josetr/cmake-language-support/issues/26

**Comment by josetr** [comment]
I forgot to ask, is syntax highlighting the only thing that isn't fully working?

Does auto-completion / signature help / rename  work?

**Comment by atsju** [comment]
autocompletion OK
signature help OK
help OK
rename OK

**Comment by josetr** [comment]
Open `Command Palette` => `Developer: Inspect editor Tokes and Scopes`

Then click over the "set" function 

![image](https://user-images.githubusercontent.com/37419832/210535187-dbf7b759-9747-4e27-9bfa-211cdf44e5a0.png)

**Comment by atsju** [comment]
![image](https://user-images.githubusercontent.com/4628382/210535866-3ef44801-1926-471e-901c-fff3063ad641.png)
![image](https://user-images.githubusercontent.com/4628382/210535956-17707dff-b8e0-4a09-b7fb-b65b7bbef3d4.png)

I add one that is working for information 
![image](https://user-images.githubusercontent.com/4628382/210536842-2e1bc053-30ff-48ce-bbaa-1b7a3c3e5bda.png)

**Comment by josetr** [comment]
Are you using a different vscode theme? If so, that may be the problem.

**Comment by atsju** [comment]
I use "Dark (visual studio)" which I believe is default one

**Comment by josetr** [comment]
I don't think it's the default one - try `Dark+ (default dark)`

**Comment by atsju** [comment]
OK this was it. Can you please fix this ?
I would rather have a coloration that doesn't fit with my theme choice than no coloration at all. 
Especially when half of coloration is working.

**Comment by josetr** [comment]
But I think this is how it's supposed to look like. If you don't like it, that's why they provide Dark+.

If you open a TypeScript / C# file, using the Dark (Visual Studio) theme, the functions won't have any colorization either.

**Comment by atsju** [comment]
Correct, other themes work with their own colors. 

I don't remember having change the theme. Thanks for support.

**Comment by USTHzhanglu** [comment]
> But I think this is how it's supposed to look like. If you don't like it, that's why they provide Dark+.
> 
> If you open a TypeScript / C# file, using the Dark (Visual Studio) theme, the functions won't have any colorization either.

I'm also having this issue and trying to find/fix it took me a lot of time, maybe we can give a hint in the introduction to help more people who are having the same issue (:
