### ISSUE TITLE
Nested continue() calls are marked as syntax error

### ISSUE THREAD

**Issue by sodevel** [josetr/cmake-language-support#5]
Example:
```cmake
foreach(foo IN LISTS bar)
  if(baz)
    continue()
  endif()
endforeach()
```

In the example above, the `continue()` call is redlined with the message `'continue' can only appear inside a 'foreach' or 'while' statement.`, however this is valid code.

**Comment by TidyScript** [comment]
![image](https://user-images.githubusercontent.com/39083672/168131464-fc5db6d9-1b72-4d26-adff-8a633755ab7c.png)

Me too.

**Comment by Thomas1664** [comment]
Also happening with `break()`

**Comment by josetr** [comment]
Fixed.
