### ISSUE TITLE
Is the source code available?

### ISSUE THREAD

**Issue by ekilmer** [josetr/cmake-language-support#6]
This looks like a cool project! Is there supposed to be source code checked in to this repo?

**Comment by josetr** [comment]
Thanks for the comment! The source code is not available. I will probably eventually release it but I'm a bit busy right now.

**Comment by ekilmer** [comment]
I'm happy to hear that you are planning to release the source!

It would be nice to state this intention in the README and/or keep an "Open" issue (also maybe stickied?) here on GitHub for future visitors with the same question.

I look forward to seeing that release and hopefully, eventually being a contributor to bug fixes or enhancements. The existing feature set looks very nice already. And I'm sure I'm not the only one who would be willing to help.

**Comment by JamiKettunen** [comment]
I'm certainly interested in this extension becoming open source as well! And yes please note the plans somewhere, I don't believe most people would start by looking at closed issues.

**Comment by jgcodes2020** [comment]
Are there any updates on this?

**Comment by astrolemonade** [comment]
Hey! I am also interested in this extension becoming open source! Great work!

**Comment by hongshui3000** [comment]
+1
