### ISSUE TITLE
Missing semantic token / highlighting

### ISSUE THREAD

**Issue by dasupradyumna** [josetr/cmake-language-support#7]
In the `list()` command, the list variable is not assigned a semantic token and hence not colored differently from ordinary string arguments / parameters. For example, in `list(APPEND EXTRA_LIBS SomeLibrary)` command, `EXTRA_LIBS` is not categorized as a variable token and lacks the appropriate highlighting.

![issue_cmake_nolistvartoken](https://user-images.githubusercontent.com/45595032/153748246-9239b434-6d65-4393-83b3-2250db61b038.png)

**Comment by josetr** [comment]
The list variable will be colored but the "MyList" variable must exist first. The behavior that you are expecting is perhaps the more correct since CMake creates the list if it doesn't exist.

**Comment by pradyudasu** [comment]
I understand your reasoning, but the same doesn't seem to apply for the `string` function (as shown in the screenshot above). The variable `MyString` did not exist when using it in the function but it was highlighted as a variable just fine. So it looks like inconsistent behavior to me.
And this extension is amazing, way ahead of its competition in the marketplace. Thanks for working hard to provide us with this beauty.

**Comment by josetr** [comment]
Fixed.
