### ISSUE TITLE
Highlight generator expressions

### ISSUE THREAD

**Issue by jgcodes2020** [josetr/cmake-language-support#8]
This would work similarly to variable expansions.

**Comment by josetr** [comment]
![image](https://user-images.githubusercontent.com/37419832/155062344-372ea031-607c-48ee-ba0e-4ca2aa3c6187.png)
Generator expression highlighting works but only for unquoted arguments. The problem with generator expressions is that, unlike variable references, they are only allowed in a few commands so highlighting them everywhere feels a bit wrong.
